#!/bin/sh
for i in `more userlist.txt `  #take input from file name userlist.txt in the same directory 
do
echo $i
adduser $i
echo "New@123" | passwd "$i" --stdin  #set hardcorded passowrd for all the users New@123
echo; echo "User $username’s password set"
done
